[package]
name = "kapun-x509"
version = "0.1.0"
edition = "2024"

[dependencies]
x509-parser = { version = "0.16.0", features = ["validate"] }
ureq = { workspace = true, optional = true }
whitespace-sifter = "2.3.7"
tracing = "^0.1"
kapun-crypto-provider = { git = "https://github.com/heidiverse/kapun-sdk.git", branch = "feature/crypto-provider" }




[features]
default = ["crl"]
uniffi = []
crl = ["dep:ureq"]

[dev-dependencies]
flate2 = "1.1.9"
tar = "0.4.45"
pem = "3.0.6"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
josekit = { git = "https://github.com/heidiverse/josekit-rs.git", default-features = false, features = [
    "rustcrypto",
    "pqc",
    "legacy-crypto"
], branch = "feature/digest-signing" }
