[package]
name = "heidi-presentation-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
name = "heidi_presentation_rust"

[dependencies]
uniffi.workspace = true
