name: Build targets

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: ["kmp", "android", "ios", "jvm"]
    runs-on: ["self-hosted", "macOS"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.platform }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Determine Gradle tasks
        id: gradle_tasks
        run: |
          targets=()
          case "${{ matrix.platform }}" in
            kmp) targets+=("KotlinMultiplatform") ;;
            android) targets+=("AndroidRelease") ;;
            ios) targets+=("IosArm64" "IosSimulatorArm64" "IosX64") ;;
            jvm) targets+=("Jvm") ;;
          esac

          tasks=""
          for target in "${targets[@]}"; do
            tasks="$tasks publish${target}PublicationToMavenLocal"
          done

          echo "tasks=$tasks" >> "$GITHUB_OUTPUT";

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup rust Tool Chain
        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
        with:
          toolchain: "1.88"

      - name: Install Android SDK components
        if: matrix.platform == 'android' || matrix.platform == 'kmp'
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager --install "ndk;28.2.13676358"

      - name: Ensure gradlew is executable
        run: chmod +x gradlew
      - name: Install Linux-Toolchain
        run: |
          brew tap messense/macos-cross-toolchains
          # install x86_64-unknown-linux-gnu toolchain
          brew install x86_64-unknown-linux-gnu
          # install aarch64-unknown-linux-gnu toolchain
          brew install aarch64-unknown-linux-gnu
          # install mingw-w64 targets
          brew install mingw-w64
      - name: Build
        env:
          UB_ARTIFACTORY_URL_ANDROID: ${{ secrets.ARTIFACTORY_URL_ANDROID }}
          UB_ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          UB_ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          IPHONEOS_DEPLOYMENT_TARGET: "16.4"
          CC_x86_64_unknown_linux_gnu: x86_64-linux-gnu-gcc
          CXX_x86_64_unknown_linux_gnu: x86_64-linux-gnu-g++
          AR_x86_64_unknown_linux_gnu: x86_64-linux-gnu-ar
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: x86_64-linux-gnu-gcc
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS: "-C link-args=-fstack-protector-all -lssp"
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
          AR_aarch64_unknown_linux_gnu: aarch64-linux-gnu-ar
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS: "-C link-args=-fstack-protector-all -lssp"
          CARGO_TARGET_X86_64-PC-WINDOWS-GNU: x86_64-w64-mingw32-gcc
        run: ./gradlew clean buildBindings ${{ steps.gradle_tasks.outputs.tasks }} --console=plain
